ProjectTracker/Controllers/CompanyController.cs
using ProjectTracker.Domain;
using ProjectTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectTracker.Controllers
{
    public class CompanyController : Controller
    {
        PTContext ptcontext = new PTContext();
        // GET: Company
        public ActionResult Index()
        {
            List<Company> companies = new List<Company>();
            companies = ptcontext.Companies.ToList();
            return View(companies);
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            Company company = new Company();
            return View(company);
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult Create(Company model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                ptcontext.Companies.Add(model);
                ptcontext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Company/Edit/5
        public ActionResult Edit(int id)
        {
            var company = ptcontext.Companies.FirstOrDefault(x => x.ID == id);
            if (company == null)
                return RedirectToAction("Index");
            return View(company);
        }

        // POST: Company/Edit/5
        [HttpPost]
        public ActionResult Edit(Company model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                var company = ptcontext.Companies.FirstOrDefault(x => x.ID == model.ID);
                company.Name = model.Name;
                ptcontext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var company = ptcontext.Companies.FirstOrDefault(x => x.ID == id);
            if (company == null)
                return RedirectToAction("Index");
            ptcontext.Companies.Remove(company);
            ptcontext.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            ptcontext.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjectTracker/Controllers/EmployeeController.cs
using ProjectTracker.Domain;
using ProjectTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectTracker.Controllers
{
    public class EmployeeController : Controller
    {

        PTContext ptcontext = new PTContext();

        public ActionResult Index()
        {
            List<Employee> companies = new List<Employee>();
            companies = ptcontext.Employees.ToList();
            return View(companies);
        }
        
        public ActionResult Create()
        {
            Employee company = new Employee();
            return View(company);
        }
        
        [HttpPost]
        public ActionResult Create(Employee model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                ptcontext.Employees.Add(model);
                ptcontext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            var employee = ptcontext.Employees.FirstOrDefault(x => x.ID == id);
            if (employee == null)
                return RedirectToAction("Index");
            return View(employee);
        }
        
        [HttpPost]
        public ActionResult Edit(Employee model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                var employee = ptcontext.Employees.FirstOrDefault(x => x.ID == model.ID);
                employee.FirstName = model.FirstName;
                employee.LastName = model.LastName;
                employee.MiddleName = model.MiddleName;
                employee.Email = model.Email;
                ptcontext.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var employee = ptcontext.Employees.FirstOrDefault(x => x.ID == id);
            if (employee == null)
                return RedirectToAction("Index");
            ptcontext.Employees.Remove(employee);
            ptcontext.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            ptcontext.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjectTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projects Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Projects Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Проекты", "Index", "Home")</li>
                    <li>@Html.ActionLink("Компании", "Index", "Company")</li>
                    <li>@Html.ActionLink("Сотрудники", "Index", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 Akyl Zholonov</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>